### ISSUE TITLE
DPI options only going to 225% make this application useless for anything 4K or above.

### ISSUE THREAD

**Issue by RHellmann** [cybertim/WpfDpiSwitcher#1]

**Comment by enimatek-nl** [comment]
Just add some lines to your liking here https://github.com/cybertim/WpfDpiSwitcher/blob/master/MainWindow.xaml.cs

**Comment by RHellmann** [comment]
Right! I had looked at the DLL and assumed it was a problem with how
windows handles DPI relative to "recommended" DPI.
It didn't even occur to me, that higher DPI options were just not enabled
in UI.

Thanks!
